### ISSUE TITLE
In default search, use site: not url:

### ISSUE THREAD

**Issue by soderlind** [yogensia/VSCodeSearchWPDocs#1]
https://github.com/yogensia/VSCodeSearchWPDocs/blob/7f832bf9f10ca4a87110fbae1cc35a0bfca218e5/package.json#L39

To search within developer.wordpress.org, you should use `site:`, not ùrl:`. Eg:

```json
 "default": "https://google.com/search?btnI&q=site:developer.wordpress.org ",
```

**Comment by yogensia** [comment]
Thanks for reporting, soderlind, I'll get this fixed in a bit.
