### ISSUE TITLE
It is not opening the documentation inside VSCode and opening a separate browser tab

### ISSUE THREAD

**Issue by meananddraj** [yogensia/VSCodeSearchWPDocs#27]
https://github.com/yogensia/VSCodeSearchWPDocs/assets/64061582/55b45f94-b47a-4ff1-9364-05887716ec7f

**Comment by yogensia** [comment]
Working on a fix for this, the extension was left alone for a while and there's many things that need updating. The WP Docs page redesign broke things further for the extension so I'll need to redo the styling as well, which might take a few days.

**Comment by meananddraj** [comment]
I was trying to modify the extension code, but somehow the packages are not being installed in my computer. Don't know why the node-sass package is causing the error

**Comment by yogensia** [comment]
Yeah, I decided to redo the whole project as I update dependencies and have a working version, just need to test some things before release. Will be moving from `node-sass` to just `sass` to handle styles. Apologies for the wait.

**Comment by meananddraj** [comment]
No worries, I tried to make a separate extension like this and it is working great as of now. Would like to make my contribution in this plugin as well.

**Comment by yogensia** [comment]
Extension is now updated and should work again!
