### ISSUE TITLE
Extend, Make Generic

### ISSUE THREAD

**Issue by brandonkal** [yogensia/VSCodeSearchWPDocs#3]
This should be pretty easy to extend to other languages/frameworks.

For instance, Go would be a prime candidate and the doc url could be opened directly:

1. Select ioutil.ReadFile
2. Look at go imports at top of current file --> "io/ioutil"
2. https://godoc.org/io/ioutil#ReadFile

For imports not from the standard library, the process is the same:

1. Select pgx.ConnConfig
2. Look at go imports --> "github.com/jackc/pgx"
3. https://godoc.org/github.com/jackc/pgx#ConnConfig

**Comment by yogensia** [comment]
This is interesting and a certain improvement, but also a bit out of scope for the extension at this point. 

Maybe it would be better to fork this into a different project before going in that direction.
